CREATE TABLE "users" (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL,
    `email` VARCHAR(30) NOT NULL UNIQUE,
    `password` VARCHAR(100) NOT NULL,
    `profileImgUrl` VARCHAR(100) NOT NULL,
    `profileImgId` VARCHAR(100) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "messages" (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `message` VARCHAR(255),
    `senderI` INT,
    `receiverId` INT,
    `sendAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("receiverId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
